export const CUP_CATEGORIES = [
  {
    id: "character",
    label: "Personaje",
    number: "01",
    color: "var(--brand-orange)",
    items: [
      "Una abuela",
      "Un mago",
      "Una skater",
      "Un adolescente",
      "Una vampira",
      "Una bruja",
      "Un gigante",
      "Una cantante",
      "Un fantasma",
      "Una científica",
      "Un robot",
      "Un esqueleto",
      "Un elefante",
      "Una gata",
      "Una araña",
      "Un dinosaurio",
      "Una rana",
      "Un murciélago",
      "Un zorro",
      "Una piña",
      "Un aguacate",
      "Un libro",
      "Un calcetín",
      "Un cactus",
      "Un cohete",
    ],
  },
  {
    id: "adjective",
    label: "Adjetivo",
    number: "02",
    color: "var(--brand-red)",
    items: [
      "tenebroso",
      "alucinante",
      "horroroso",
      "muy fashion",
      "aventurero",
      "asqueroso",
      "gigantesco",
      "veloz",
      "intrigante",
      "divertido",
      "un poco loco",
      "miedoso",
      "tímido",
      "orgulloso",
      "famoso",
      "salvaje",
      "amoroso",
      "estudioso",
      "pacífico",
      "ambicioso",
      "impaciente",
      "desastroso",
      "sensible",
    ],
  },
  {
    id: "action",
    label: "Acción",
    number: "03",
    color: "var(--brand-cyan)",
    items: [
      "haciendo una pócima",
      "bailando en mitad de la calle",
      "cocinando un potaje asqueroso",
      "corriendo muy despacio",
      "cayendo de un precipicio",
      "meditando",
      "haciendo magia",
      "contestando en un concurso",
      "escondiéndose",
      "haciendo skate",
      "nadando con flotador",
      "olvidándose de algo importante",
      "saltando en una colchoneta",
      "tocando el arpa",
      "saltando a la cuerda",
      "cantando fatal",
      "haciendo ejercicio",
      "pintando un mural",
      "durmiendo de pie",
      "escribiendo un poema",
    ],
  },
  {
    id: "detail",
    label: "Complemento",
    number: "04",
    color: "var(--brand-lime)",
    items: [
      "con espinas",
      "con unas zapatillas molonas",
      "con un traje de plumas",
      "con alas de mariposa",
      "con una barba larguísima",
      "con joyas carísimas",
      "con una gorra de rapero",
      "con unos pantalones enormes",
      "con un micrófono",
      "con una bufanda larguísima",
      "con un vestido de fiesta",
      "con un bañador divertido",
      "con una capa de superhéroe",
      "con unos dientes falsos",
      "con unos zapatos enormes",
      "con un uniforme de lunares",
      "con un collar de flores",
      "con un jersey que le hace invisible",
      "con una concha de caracol",
      "con una cabeza extra",
    ],
  },
] as const;

export type CauldronOption = {
  name: string;
  emoji: string;
  color: string;
};

export const CHARACTERS: readonly CauldronOption[] = [
  { name: "Vampira", emoji: "🧛‍♀️", color: "#d92f68" },
  { name: "Bruja", emoji: "🧙‍♀️", color: "#9447b9" },
  { name: "Robot", emoji: "🤖", color: "#218aa1" },
  { name: "Dragón", emoji: "🐉", color: "#d76b22" },
  { name: "Elfa", emoji: "🧝‍♀️", color: "#39825f" },
  { name: "Pirata", emoji: "🏴‍☠️", color: "#8f6d20" },
  { name: "Fantasma", emoji: "👻", color: "#7466a8" },
  { name: "Mago", emoji: "🧙‍♂️", color: "#694bb5" },
  { name: "Hada", emoji: "🧚", color: "#ce3c74" },
  { name: "Sirena", emoji: "🧜‍♀️", color: "#248c89" },
  { name: "Alien", emoji: "👽", color: "#4d8b43" },
  { name: "Astronauta", emoji: "🧑‍🚀", color: "#347aa5" },
  { name: "Panadera", emoji: "🥖", color: "#a06429" },
  { name: "Detective", emoji: "🕵️", color: "#57546d" },
  { name: "Alquimista", emoji: "⚗️", color: "#357b68" },
  { name: "Barda", emoji: "🎻", color: "#bd4163" },
  { name: "Inventora", emoji: "🛠️", color: "#286f89" },
  { name: "Cartógrafo", emoji: "🗺️", color: "#8b6822" },
  { name: "Relojera", emoji: "⏰", color: "#946338" },
  { name: "Guardián del bosque", emoji: "🌲", color: "#3c7950" },
];

export const PERSONALITIES: readonly CauldronOption[] = [
  { name: "Tímido", emoji: "🙈", color: "#8d56a4" },
  { name: "Sarcástico", emoji: "🙃", color: "#c23966" },
  { name: "Heroico", emoji: "🦸", color: "#977323" },
  { name: "Caótico", emoji: "🌪️", color: "#bf632b" },
  { name: "Melancólico", emoji: "🌧️", color: "#3d7490" },
  { name: "Curioso", emoji: "🔎", color: "#318065" },
  { name: "Misterioso", emoji: "🌙", color: "#7051a2" },
  { name: "Adorable", emoji: "💗", color: "#c23e70" },
  { name: "Sabio", emoji: "📚", color: "#836827" },
  { name: "Impulsivo", emoji: "⚡", color: "#c46527" },
  { name: "Leal", emoji: "🤝", color: "#2d7c63" },
  { name: "Soñador", emoji: "☁️", color: "#7561a6" },
  { name: "Bromista", emoji: "🎭", color: "#a17620" },
  { name: "Protector", emoji: "🛡️", color: "#36768e" },
  { name: "Torpe", emoji: "🫠", color: "#a57925" },
  { name: "Optimista", emoji: "☀️", color: "#9c7721" },
  { name: "Rebelde", emoji: "🔥", color: "#bc3e38" },
  { name: "Perfeccionista", emoji: "📐", color: "#3d718f" },
  { name: "Excéntrico", emoji: "🎩", color: "#8e4e9c" },
  { name: "Imprevisible", emoji: "🎲", color: "#734f9f" },
];

export const CONTEXTS: readonly CauldronOption[] = [
  { name: "en un apocalipsis zombi", emoji: "🧟", color: "#4c7e45" },
  { name: "en la Edad Media", emoji: "🏰", color: "#967124" },
  { name: "en una ciudad ciberpunk", emoji: "🌃", color: "#317992" },
  { name: "en una escuela de magia", emoji: "🏫", color: "#7950a1" },
  { name: "en el espacio profundo", emoji: "🌌", color: "#3b7196" },
  { name: "en el Olimpo", emoji: "⚡", color: "#9a7623" },
  { name: "en una selva encantada", emoji: "🌿", color: "#347c56" },
  { name: "en un desierto mágico", emoji: "🏜️", color: "#b46b2d" },
  { name: "en una ciudad steampunk", emoji: "⚙️", color: "#9a692f" },
  { name: "en una colonia de Marte", emoji: "🪐", color: "#b24452" },
  { name: "en un reino sumergido", emoji: "🌊", color: "#2b7c91" },
  { name: "en un bosque maldito", emoji: "🌲", color: "#4d6843" },
  { name: "en una ciudad flotante", emoji: "🏙️", color: "#367f7a" },
  { name: "en un carnaval eterno", emoji: "🎪", color: "#bc4b70" },
  { name: "en una biblioteca infinita", emoji: "📚", color: "#754f97" },
  { name: "en un pueblo fantasma", emoji: "👻", color: "#69647f" },
  { name: "en una feria de monstruos", emoji: "🎠", color: "#41815c" },
  { name: "en un circo de medianoche", emoji: "🌙", color: "#a1406f" },
  { name: "en el reino de los sueños", emoji: "💭", color: "#6f61a4" },
  { name: "en un tren que no existe", emoji: "🚂", color: "#775c45" },
];

export const BIO_TEMPLATES = [
  (character: string, personality: string, context: string) =>
    `${character}, de carácter ${personality.toLowerCase()}, intenta pasar desapercibido ${context}. Lo difícil es que cada vez que miente aparece una pequeña nube sobre su cabeza.`,
  (character: string, personality: string, context: string) =>
    `Nadie esperaba que ${character.toLowerCase()} tan ${personality.toLowerCase()} se convirtiera en leyenda ${context}. Todo empezó con un mapa dibujado al revés.`,
  (character: string, personality: string, context: string) =>
    `${character} ha llegado ${context} con una personalidad ${personality.toLowerCase()} y un secreto: puede escuchar lo que piensan los objetos perdidos.`,
  (character: string, personality: string, context: string) =>
    `Sobrevivir ${context} no es fácil para ${character.toLowerCase()} tan ${personality.toLowerCase()}. Por suerte, lleva tres galletas y una idea imposible.`,
] as const;
